export const projects = [
    {
        title: 'Vocabulary Crossword Puzzles',
        description: 'A web site for learning new vocabulary words through interactive crossword puzzles, with a focus on enhancing language skills and retention.',
        image: '',
        technologies: ['TypeScript', 'React', 'Next.js', 'Tailwind CSS', 'Node.js', 'PostgreSQL', 'Supabase'],
        liveUrl: 'https://vocabulary-crossword-puzzles.vercel.app/',
        // githubUrl: 'https://github.com/Akushu2357/Vocabulary-Crossword-Puzzles',
        skills: [
            { name: 'TypeScript', category: 'Frontend'},
            { name: 'React', category: 'Frontend'},
            { name: 'Next.js', category: 'Frontend'},
            { name: 'Tailwind CSS', category: 'Styling'},
            { name: 'Responsive Design', category: 'Frontend'},
            { name: 'Node.js', category: 'Backend'},
            { name: 'PostgreSQL', category: 'Database' },
            { name: 'Supabase', category: 'Database' },
            { name: 'Vercel', category: 'Deployment' },
            { name: 'Integration API', category: 'Backend' },
            { name: 'OAuth 2.0', category: 'Security' },
        ],
        completed: true,
    },
    {
        title: 'Automated Datafricks UI workflows for Validateing Data Integrity',
        description: 'A project focused on automating UI workflows in Databricks to validate data integrity, ensuring accurate and reliable data processing.',
        image: '',
        technologies: ['Python', 'PyQt', 'Selenium', 'Robot Framework', 'Playwright', 'SQL', 'Databricks'],
        // liveUrl: '',
        // githubUrl: '',
        skills: [
            { name: 'Python', category: 'Programming Language' },
            { name: 'PyQt', category: 'GUI Development' },
            { name: 'Selenium', category: 'Testing Framework' },
            { name: 'Robot Framework', category: 'Testing Framework' },
            { name: 'Playwright', category: 'Testing Framework' },
            { name: 'SQL', category: 'Database' },
            { name: 'Databricks', category: 'Data Platform' },
            { name: 'Automated Testing', category: 'Testing' },
        ],
        completed: true,
    },
    {
        title: 'Thai Labor Law Chatbot Web Application',
        description: 'A chatbot web application designed to provide information and guidance on Thai labor laws and regulations. With chatbot and labor law knowledge, the application aims to assist users in understanding their rights and obligations in the workplace.',
        image: '',
        technologies: ['Python', 'FastAPI', 'Robot Framework', 'Supabase', 'PostgreSQL', 'JavaScript', 'React', 'Javascript', 'Netlify', 'VMware', 'Google Cloud Platform', 'LLM'],
        // liveUrl: '',
        // githubUrl: '',
        skills: [
            { name: 'Python', category: 'Programming Language' },
            { name: 'FastAPI', category: 'Backend Framework' },
            { name: 'Robot Framework', category: 'Testing Framework' },
            { name: 'Supabase', category: 'Database' },
            { name: 'PostgreSQL', category: 'Database' },
            { name: 'JavaScript', category: 'Frontend' },
            { name: 'React', category: 'Frontend Framework' },
            { name: 'Netlify', category: 'Deployment' },
            { name: 'VMware', category: 'Virtualization' },
            { name: 'Google Cloud Platform', category: 'Cloud Services' },
            { name: 'LLM', category: 'Artificial Intelligence' },
            { name: 'OAuth 2.0', category: 'Security' },
        ],
        completed: true,
    },
    {
        title: 'Personal Portfolio Website',
        description: 'A personal portfolio website showcasing my skills, projects, and experiences as a software developer. The website is designed to provide an overview of my work and achievements in the field of technology.',
        image: '',
        technologies: ['JavaScript', 'React', 'Vite.js', 'Tailwind CSS', 'Node.js', 'GitHub Pages'],
        liveUrl: 'https://akushu2357.github.io/portfolio/',
        githubUrl: 'https://github.com/Akushu2357/portfolio',
        skills: [
            { name: 'JavaScript', category: 'Frontend' },
            { name: 'React', category: 'Frontend Framework' },
            { name: 'Vite.js', category: 'Build Tool' },
            { name: 'Tailwind CSS', category: 'Styling' },
            { name: 'Node.js', category: 'Backend' },
            { name: 'GitHub Pages', category: 'Deployment' },
        ],
        completed: true,
    },
    {
        title: 'Audio Classification and Noise Reduction System',
        description: 'A system for classifying audio signals and reducing noise in audio recordings. The system uses machine learning algorithms to identify and separate different types of audio signals, and applies noise reduction techniques to improve the quality of the audio.',
        image: '',
        technologies: ['Python', 'sklearn', 'XGBoost', 'Catboost', 'LightGBM', 'matplotlib', 'pandas', 'NumPy'],
        liveUrl: '',
        githubUrl: 'https://github.com/Akushu2357/audio-classification',
        skills: [
            { name: 'Python', category: 'Programming Language' },
            { name: 'XGBoost', category: 'Machine Learning' },
            { name: 'Catboost', category: 'Machine Learning' },
            { name: 'LightGBM', category: 'Machine Learning' },
            { name: 'matplotlib', category: 'Data Visualization' },
            { name: 'pandas', category: 'Data Manipulation' },
            { name: 'Scipy', category: 'Scientific Computing' },
            { name: 'NumPy', category: 'Numerical Computing' },
        ],
        completed: true,
        // liveUrl: '',
        // githubUrl: 'https://github.com/Akushu2357/audio-classification',
    },
    {
        title: 'KOO-KIN Social Web Application for Food-based Connections',
        description: 'A social web application that connects users based on their food preferences and interests. The platform allows users to find someone with similar tastes, discover new restaurants, and connect with others who share similar culinary tastes.',
        image: '',
        technologies: ['JavaScript', 'React', 'Node.js', 'Express.js', 'MongoDB', 'Mongoose', 'Tailwind CSS'],
        // liveUrl: '',
        githubUrl: 'https://github.com/SOtwoX1/Project-SE',
        skills: [
            { name: 'JavaScript', category: 'Frontend' },
            { name: 'React', category: 'Frontend Framework' },
            { name: 'Node.js', category: 'Backend' },
            { name: 'Express.js', category: 'Backend Framework' },
            { name: 'MongoDB', category: 'Database' },
            { name: 'Mongoose', category: 'Database ODM' },
            { name: 'Tailwind CSS', category: 'Styling' },
        ],
        completed: true,
    }
];

export const countCompletedProjects = () => {
    return projects.filter(project => project.completed).length;
}