export const projects = [
    {
        title: 'Vocabulary Crossword Puzzles',
        description: 'An interactive vocabulary learning platform that generates crossword puzzles from English vocabulary data. Built with a modern full-stack architecture featuring React, Next.js, PostgreSQL, authentication, and API integration.',
        image: '',
        technologies: [
            'TypeScript',
            'React',
            'Next.js',
            'Tailwind CSS',
            'Node.js',
            'PostgreSQL',
            'Supabase',
            'Vercel',
        ],
        liveUrl: 'https://vocabulary-crossword-puzzles.vercel.app/',
        // githubUrl: 'https://github.com/Akushu2357/Vocabulary-Crossword-Puzzles',
        skills: [
            { name: 'TypeScript', category: 'Frontend' },
            { name: 'React', category: 'Frontend' },
            { name: 'Next.js', category: 'Frontend' },
            { name: 'Tailwind CSS', category: 'Styling' },
            { name: 'Responsive Design', category: 'Frontend' },
            { name: 'Node.js', category: 'Backend' },
            { name: 'PostgreSQL', category: 'Database' },
            { name: 'Supabase', category: 'Database' },
            { name: 'REST API', category: 'Testing' },
            { name: 'OAuth 2.0', category: 'Security' },
            { name: 'Vercel', category: 'Deployment' },
        ],
        completed: false,
    },
    {
        title: 'Databricks Data Integrity Test Automation',
        description: 'An automated testing solution for validating data integrity in Databricks workflows. Built internal GUI tools and automated UI workflows to reduce repetitive manual testing and improve validation efficiency.',
        image: '',
        technologies: [
            'Python',
            'PyQt',
            'Selenium',
            'Robot Framework',
            'Playwright',
            'SQL',
            'Databricks',
        ],
        skills: [
            { name: 'Python', category: 'Programming' },
            { name: 'PyQt', category: 'UX' },
            { name: 'Selenium', category: 'Testing' },
            { name: 'Robot Framework', category: 'Testing' },
            { name: 'Playwright', category: 'Testing' },
            { name: 'SQL', category: 'Database' },
            { name: 'Databricks', category: 'Data' },
            { name: 'Test Automation', category: 'Testing' }
        ],
        completed: true,
    },
    {
        title: 'Thai Labor Law Chatbot',
        description: 'A web-based AI chatbot designed to help users understand Thai labor laws through natural-language questions. The system combines a React frontend, FastAPI backend, PostgreSQL database, and LLM-based retrieval to provide relevant legal information.',
        image: '',
        technologies: [
            'Python',
            'FastAPI',
            'React',
            'JavaScript',
            'PostgreSQL',
            'Supabase',
            'LLM',
            'Google Cloud',
            'Netlify',
        ],
        // liveUrl: '',
        // githubUrl: '',
        skills: [
            { name: 'Python', category: 'Backend' },
            { name: 'FastAPI', category: 'Backend' },
            { name: 'React', category: 'Frontend' },
            { name: 'PostgreSQL', category: 'Database' },
            { name: 'Supabase', category: 'Database' },
            { name: 'LLM', category: 'AI' },
            { name: 'REST API', category: 'Testing' },
            { name: 'OAuth 2.0', category: 'Security' },
            { name: 'Google Cloud', category: 'Cloud' },
            { name: 'Netlify', category: 'Deployment' },
        ],
        completed: true,
    },
    {
        title: 'Personal Portfolio Website',
        description: 'A responsive personal portfolio built to showcase my software engineering experience, technical projects, and certifications. Designed and developed as a single-page application with React and Tailwind CSS.',
        image: '',
        technologies: [
            'JavaScript',
            'React',
            'Vite',
            'Tailwind CSS',
            'GitHub Pages'
        ],
        liveUrl: 'https://akushu2357.github.io/portfolio/',
        githubUrl: 'https://github.com/Akushu2357/portfolio',
        skills: [
            { name: 'JavaScript', category: 'Frontend' },
            { name: 'React', category: 'Frontend' },
            { name: 'Vite', category: 'Frontend' },
            { name: 'Tailwind CSS', category: 'Styling' },
            { name: 'Responsive Design', category: 'UX' },
            { name: 'GitHub Pages', category: 'Deployment' },
        ],
        completed: true,
    },
    {
        title: 'Audio Classification',
        description: 'A machine learning system for classifying audio signals and distinguishing different types of sounds and noise. The project covers data preprocessing, feature engineering, model training, evaluation, and visualization using multiple machine learning algorithms.',
        image: '',
        technologies: [
            'Python',
            'Scikit-learn',
            'XGBoost',
            'CatBoost',
            'LightGBM',
            'Pandas',
            'NumPy',
            'Matplotlib',
        ],
        // liveUrl: '',
        // githubUrl: '',
        skills: [
            { name: 'Python', category: 'Programming' },
            { name: 'Scikit-learn', category: 'AI' },
            { name: 'XGBoost', category: 'AI' },
            { name: 'CatBoost', category: 'AI' },
            { name: 'LightGBM', category: 'AI' },
            { name: 'Pandas', category: 'Data' },
            { name: 'NumPy', category: 'Data' },
            { name: 'Matplotlib', category: 'Visualization' },
        ],
        completed: true
    },
    {
        title: 'KOO-KIN — Food Social Web Application',
        description: 'A social web application that connects users based on their food preferences. The platform allows users to discover restaurants, find people with similar tastes, and interact through a shared food-focused community.',
        image: '',
        technologies: [
            'JavaScript',
            'React',
            'Node.js',
            'Express.js',
            'MongoDB',
            'Mongoose',
            'Tailwind CSS',
        ],
        // liveUrl: '',
        githubUrl: 'https://github.com/SOtwoX1/Project-SE',
        skills: [
            { name: 'JavaScript', category: 'Frontend' },
            { name: 'React', category: 'Frontend' },
            { name: 'Node.js', category: 'Backend' },
            { name: 'Express.js', category: 'Backend' },
            { name: 'MongoDB', category: 'Database' },
            { name: 'Mongoose', category: 'Database' },
            { name: 'Tailwind CSS', category: 'Styling' },
        ],
        completed: true,
    }
];

export const countCompletedProjects = () => {
    return projects.filter(project => project.completed).length;
}

export const getImageUrl = (path) => {
    return new URL(path ? path : '../projects/default.jpg', import.meta.url).href;
};